## the host variable on the file is not valid, you need to adjust it before testing this api.

openapi: 3.0.3
info:
  title: Whatsapp toolbox
  description: Fetch whatsapp profile pics and validate whatsapp number registration
  version: "1.0.0"
  contact:
    name: inutil labs
    email: contact@inutil-labs.com
servers:
  - url: https://{URL}
    description: ""
    variables:
      URL:
        default: https://watoolbox.inutil-labs.com
paths:
  /about:
    get:
      tags: []
      summary: About info
      description: the about info that a whatsapp user set on the status.
      parameters:
        - name: phone
          in: query
          description: "phone number on the request"
          required: false
          schema:
            type: integer
            default: 34605797764
            description: a valid phone number, including country code (without +, or 00 at the begining)
      responses:
        "200":
          description: the about message and the time-date it was set.
      security: []
      operationId: /about
  /wchk:
    get:
      tags: []
      summary: Validate WA number
      description: checks if the number is registered on the whatsapp network
      parameters:
        - name: phone
          in: query
          description: "phone number on the request"
          required: false
          schema:
            type: integer
            default: 34666777888
            description: a valid phone number, including country code (without +, or 00 at the begining)
      responses:
        "200":
          description: true or false, depending of the registration status of the number on the request
      security: []
      operationId: /wchk
  /wspic/b64:
    get:
      tags: []
      summary: Picture base64
      description: fetchs the base64 file type of the whatsapp profile picture of the number on the request
      parameters:
        - name: phone
          in: query
          description: "phone number on the request"
          required: false
          schema:
            type: integer
            default: 34605797764
            description: a valid phone number, including country code (without +, or 00 at the begining)
      responses:
        "200":
          description: a base64 binary buffer
      security: []
      operationId: /wspic/b64
  /wspic/png:
    get:
      tags: []
      summary: Picture jpg
      description: fetchs the png type file of the whatsapp profile picture of the number on the request
      parameters:
        - name: phone
          in: query
          description: "phone number on the request"
          required: false
          schema:
            type: integer
            default: 34605797764
            description: a valid phone number, including country code (without +, or 00 at the begining)
      responses:
        "200":
          description: a png file
      security: []
      operationId: /wspic/png
  /wspic/url:
    get:
      tags: []
      summary: Picture url
      description: fetchs the public url of the whatsapp profile picture of the number on the request
      parameters:
        - name: phone
          in: query
          description: "phone number on the request"
          required: false
          schema:
            type: integer
            default: 34605797764
            description: a valid phone number, including country code (without +, or 00 at the begining)
      responses:
        "200":
          description: a public url to fetch the whatsapp picture
      security: []
      operationId: /wspic/url
